config/routes.rb
Rails.application.routes.draw do

  

  
  get 'admin/show_distributions'

  get "log_in" => "sessions#new", :as => "log_in"
  post "log_in" => "sessions#create"
  delete "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  
  post 'end_users/add_ready'
  post 'end_users/add_iready'
  post "end_users/update_ready"
  post "end_users/update_iready"
  get 'distributions/index'
  get 'distributions/edit'
  get 'distributions/create'
  get 'distributions/districts'
  post 'distributions/district_id'
  post 'distributions/update'
  root :to => "distributions#index"

  resources :distributions
  resources :districts
  resources :users

end

app/models/distribution.rb
  class Distribution < ActiveRecord::Base
  attr_accessible :street, :city, :state, 
          :contact_name, :creation_date, 
          :final_quote_id, :po_number, 
          :i_ready_orders_attributes,
          :ready_orders_attributes, :zip,
          :districts_attributes,
          :district_id
  validates :district_id, presence: true
  has_many :i_ready_orders
  has_many :ready_orders

  belongs_to :district
  belongs_to :user
  accepts_nested_attributes_for :i_ready_orders, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :ready_orders, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true


  def distribution_info
    schools = School.where(district_id: self.district_id).collect { |e| [e.pid, e.name, e.enrollment] }
    d_with_district = self.attributes
    d_with_district["district"] = District.where(pid: self.district_id)[0]
    d_with_district["creation_date"] = d_with_district["creation_date"]? d_with_district["creation_date"].strftime("%F"): nil
    district_options = []
    if d_with_district["district"]
      state = d_with_district["district"]["state"]
      district_options = District.where(state: state).pluck('name').uniq
    end

    i_ready_users = IReadyOrder.where(distribution_id: self.id).to_a
    ready_users = ReadyOrder.where(distribution_id: self.id).to_a
    i_ready_users.map! do |e|
      e.attributes_with_school
    end
    ready_users.map! do |e|
      e.attributes_with_school
    end
    {
    distribution: d_with_district,
    schools: schools,
    district_options: district_options,
    i_ready_users: i_ready_users,
    ready_users: ready_users
    }
  end

  def self.displayColumns
    [
      "contact_name",
      "creation_date",
      "final_quote_id",
      "po_number",
      "street",
      "city",
      "state",
      "zip"
    ]
  end

  def to_csv
    dist_csv_string = CSV.generate do |csv|
      csv << [""]
      csv << ["", "Distribution Template"]
      #do the distribution header
      Distribution.displayColumns.each do |c|
        attribute = self.attributes[c]
        if c == "creation_date"
          attribute = attribute.strftime("%F")
        end
        csv << ['',c.titleize, attribute]
      end
      csv << [""]
      csv << ["", "Ready Users"]
      #do ready orders
      # column names for orders, school and ReadyOrders
      csv << [""]+ReadyOrder.displayColumns.map { |e| e.titleize } 
      ready_orders = ReadyOrder.where(distribution_id: self.id).to_a
      ready_orders.each do |ready|
        csv << [""]+ready.displayArray
      end

      csv << [""]
      csv << [""]
      csv << ["", "I-Ready Users"]
      # header row including order, school and iready column names
      csv << [""]+IReadyOrder.displayColumns.map { |e| e.titleize }
      i_ready_orders = IReadyOrder.where(distribution_id: self.id).to_a
      i_ready_orders.each do |iready|
        csv << [""]+iready.displayArray
      end
    end
    return dist_csv_string    
  end

end

app/controllers/distributions_controller.rb
class DistributionsController < ApplicationController

  def create
  	respond_to do |format|
      state = params["district_state"]
      name = params["district_name"]
      district_id = District.where(state: state, name:name).pluck(:pid)
      distribution = Distribution.new(params[:distribution])
      distribution.user_id = current_user["id"]
      distribution.district_id = district_id[0]
      if distribution.save
        format.html{redirect_to '/distributions/index', notice: 'successfully created distribution'}
  		  format.json{render json: distribution.distribution_info}
      else
        format.html{redirect_to '/distributions/index', notice: 'failed to create a distribution'}
        format.json{render :json => { :errors => distribution.errors.full_messages }, :status => 422}
  		end
    end

  end

  def school_id
    respond_to do |format|
      district_id = params[:district]
      school_name =   params[:school]
      school_id = School.where(district_id: district_id, name: school_name).pluck(:pid)
      format.json {render json: school_id}
    end
  end

  def district_id
    respond_to do |format|
      state = params[:state]
      district_name = params[:name]
      district_id = District.where(state: state, name: district_name).pluck(:pid)
      schools = School.where(district_id: district_id).pluck(:name)
      format.json {render json: [district_id, schools]}
      # format.html {}
    end
  end

  def index
    if not current_user
      redirect_to log_in_path
    else
      user_id = current_user['id']
      @distributions = Distribution.where(user_id: user_id).order(:district_id)
      distribution_information = []
      @distributions.each do |d|
        distribution_information << d.distribution_info
      end

      respond_to do |format|
        format.html {render "index"}
        format.json {render json: distribution_information}
      end
    end
  end
  
  def show
    id = params['id']
    @distribution = Distribution.find(id)
    @distribution.i_ready_orders.build
    @distribution.ready_orders.build
    respond_to do |format|
      format.csv {send_data @distribution.to_csv}
      format.html
      format.json{render json: @distribution}
    end
  end

  def update
    respond_to do |format|
      if params["field"] == "district_id"
        value = params["value"]
        params["value"] = District.where(state: value["state"], name: value["name"]).pluck('pid')[0]
      end
      distribution = Distribution.find_by(id:params["id"])
      puts ({params["field"] => params["value"]})
      if distribution.update(params["field"]=> params["value"])
        format.json { render json: {status: "ok"}}
      else
        puts distribution.errors.full_messages
        format.html { render :edit }
        format.json { render json: distribution.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end


  def districts
    respond_to do |format|
      state = params[:state]
      districts = District.where(state: state[:name]).pluck('name').uniq
      format.json {render json: districts}
      format.html {}
    end
  end
   
end

app/helpers/distributions_helper.rb
module DistributionsHelper
	# def link_to_remove_fields(name, f)
	# 	f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	# end
	
	# def link_to_add_fields(name, f, association)
	# 	new_object = f.object.class.reflect_on_association(association).klass.new
	# 	fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	# 		render(association.to_s.singularize + "_fields", :f => builder)
	# 	end
	# 	link_to_function(name, h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
	# end
end

app/views/distributions/_distribution_form.slim
= form_tag "/distributions/district_id", id:"district_form" do
	= render partial: 'state_selector'
	.form-group.ui-widget.ui-front
		= label_tag :name
		= text_field_tag :name,"", id:'district_auto', class: 'form-control', required: true 

= form_for @distribution do |f|
	/optional
	/ a.btn.btn-primary#add_address href="#" Add Address
	
	.form-group#address
		h3 Distribution address
		p leave blank if not applicable
		.form-group
			=f.label :contact_name 
			=f.text_field :contact_name, class: 'form-control', required: false
		.form-group
			=f.label :street 
			=f.text_field :street, class: 'form-control', required: false
		.form-group.col-sm-4
			=f.label :city 
			=f.text_field :city, class: 'form-control', required: false
		.col-sm-4
			= render "state_selector"	
		.form-group.col-sm-3
			=f.label :zip 
			=f.text_field :zip, class: 'form-control', required: false 
	/end optional
	.form_group#info
		h3 Distribution Info
		.form-group
			=f.label :creation_date 
			=f.text_field :creation_date, class: 'form-control', required: true
		.form-group
			=f.label 'Final Quote ID' 
			=f.text_field :final_quote_id, class: 'form-control', required: true
		.form-group
			=f.label :po_number 
			=f.text_field :po_number,	 class: 'form-control', required: true

		

app/views/distributions/_distribution_modal.slim
.modal.fade#distributionModal tabindex="-1" role="dialog" aria-labelledby="distributionModal"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4.modal-title#distributionModal Add Distribution
      .modal-body
        = render partial: "distribution_form"

      .modal-footer
        button.btn.btn-default type="button" data-dismiss="modal" Close
        button.btn.btn-primary.save_changes#submit_distribution type="submit" name="commit" value="Create Distribution" save
        / <input type="submit" name="commit" value="Create Distribution">

app/views/distributions/_distribution_row.slim
tr
	td
		= distro.user_id
	td 
		= distro.creation_date
	td 
		= distro.final_quote_id
	td 
		= distro.po_number
	td 
		= distro.district.nil? ? 'Error: No district' : distro.district.name
	td
		= distro.district.nil? ? 'Error: No district' : distro.district.state
	td
		= distro.orders.count
	td
		button.btn.btn-primary.end_user.iready type="button"  data-toggle="modal" data-target="#ireadyModal" data-schools=@schoolMap[distro.district_id] data-distribution=distro.id
				add IReady User
	td	
		button.btn.btn-primary.end_user.ready type="button"  data-toggle="modal" data-target="#readyModal" data-schools=@schoolMap[distro.district_id] data-distribution=distro.id
				add Ready User
	/ td
		/ a href="#edit" edit
	td
		= link_to "show detail", distribution_path(distro)

app/views/distributions/_end_user_modal.slim
.modal.fade#endUserModal tabindex="-1" role="dialog" aria-labelledby="endUserModal"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4.modal-title#endUserModal Add End User
      .modal-body
        = render partial: "order"

      .modal-footer
        button.btn.btn-default type="button" data-dismiss="modal" Close
        button.btn.btn-primary.save_changes type="button" save changes

app/views/distributions/_iready_modal.slim
.modal.fade#ireadyModal tabindex="-1" role="dialog" aria-labelledby="ireadyModal"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4.modal-title#ireadyModal Add IReady User
      .modal-body
        = render "iready_order"
      .modal-footer
        button.btn.btn-default type="button" data-dismiss="modal" Close
        button.btn.btn-primary.save_changes#submit_iready type="button" name="commit" value="Create iready" save
        / <input type="submit" name="commit" value="Create Distribution">

app/views/distributions/_iready_order.slim
/ _IReady_Order.slim
=form_tag "/end_users/add_order", id: "new_iready"
	= render 'order'
	h3 IReady Group	
	= fields_for :i_ready_orders do |i|
		.form_group
			=i.label "subject"
			=i.select "subject", nil, {}, {class: 'form-control'}
				option value="math" math
				option value="reading" reading
				option value="math & reading" math & reading

		.form_group
			=i.label "toolbox"
			=i.check_box "toolbox", as: :boolean , class: 'form-control'
		.form_group
			=i.label "enrollment"
			=i.number_field "enrollment", class: 'form-control'

app/views/distributions/_order.slim
/ _order.slim
/ #order style="display: none"

= fields_for :order
	= hidden_field(:distribution, :id, {class: "distribution_id"})
	.form-group
		label.col-sm-2 for="School" School Name
		.col-sm-10
	    select.form-control.school name="school"
	      option value=""   N/A
	.form-group
		=label_tag :Contact 
		=text_field_tag :contact_name,"",	 class: 'form-control', required: false
	

app/views/distributions/_ready_modal.slim
.modal.fade#readyModal tabindex="-1" role="dialog" aria-labelledby="readyModal"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4.modal-title#readyModal Add Ready User
      .modal-body
        = render "ready_order"
      .modal-footer
        button.btn.btn-default type="button" data-dismiss="modal" Close
        button.btn.btn-primary.save_changes#submit_ready type="button" name="commit" value="Create ready" save
        / <input type="submit" name="commit" value="Create Distribution">

app/views/distributions/_ready_order.slim
/ _add_Ready_Order.slim
=form_tag "/end_users/add_order", id: "new_ready"
	= render "order"
	h3 Ready Group
	= fields_for :ready_order do |r|

		=r.select "subject", nil, {}, {class: "form-control"}
			option value="math" math
			option value="reading" reading
			option value="writing" writing
			option value="math & reading" math & reading
			option value="reading & writing" reading & writing
			option value="writing & math" writing & math
			option value="writing & math & reading" writing & math & reading
		=r.label "grade 1 teacher"	
		=r.number_field  "grade_1_teacher"	
		=r.label "grade 1 student"
		=r.number_field  "grade_1_student"
		=r.label "grade 2 teacher"
		=r.number_field  "grade_2_teacher"
		=r.label "grade 2 student"
		=r.number_field  "grade_2_student"
		=r.label "grade 3 teacher"
		=r.number_field  "grade_3_teacher"
		=r.label "grade 3 student"
		=r.number_field  "grade_3_student"
		=r.label "grade 4 teacher"
		=r.number_field  "grade_4_teacher"
		=r.label "grade 4 student"
		=r.number_field  "grade_4_student"
		=r.label "grade 5 teacher"
		=r.number_field  "grade_5_teacher"
		=r.label "grade 5 student"
		=r.number_field  "grade_5_student"
		=r.label "grade 6 teacher"
		=r.number_field  "grade_6_teacher"
		=r.label "grade 6 student"
		=r.number_field  "grade_6_student"
		=r.label "grade 7 teacher"
		=r.number_field  "grade_7_teacher"
		=r.label "grade 7 student"
		=r.number_field  "grade_7_student"
		=r.label "grade 8 teacher"
		=r.number_field  "grade_8_teacher"
		=r.label "grade 8 student"
		=r.number_field  "grade_8_student"

app/views/distributions/_school_selector.slim
label.col-sm-2 for="School" class=""School Name
.col-sm-10
    select class="form-control" id="school" name="school"
        option value=""   N/A

app/views/distributions/_state_selector.slim
label.col-sm-2 for="state" class=""State
.col-sm-10
    select class="form-control" id="state" name="state"
        option value=""   N/A
        option value="AK" Alaska
        option value="AL" Alabama
        option value="AR" Arkansas
        option value="AZ" Arizona
        option value="CA" California
        option value="CO" Colorado
        option value="CT" Connecticut
        option value="DC" District of Columbia
        option value="DE" Delaware
        option value="FL" Florida
        option value="GA" Georgia
        option value="HI" Hawaii
        option value="IA" Iowa
        option value="ID" Idaho
        option value="IL" Illinois
        option value="IN" Indiana
        option value="KS" Kansas
        option value="KY" Kentucky
        option value="LA" Louisiana
        option value="MA" Massachusetts
        option value="MD" Maryland
        option value="ME" Maine
        option value="MI" Michigan
        option value="MN" Minnesota
        option value="MO" Missouri
        option value="MS" Mississippi
        option value="MT" Montana
        option value="NC" North Carolina
        option value="ND" North Dakota
        option value="NE" Nebraska
        option value="NH" New Hampshire
        option value="NJ" New Jersey
        option value="NM" New Mexico
        option value="NV" Nevada
        option value="NY" New York
        option value="OH" Ohio
        option value="OK" Oklahoma
        option value="OR" Oregon
        option value="PA" Pennsylvania
        option value="PR" Puerto Rico
        option value="RI" Rhode Island
        option value="SC" South Carolina
        option value="SD" South Dakota
        option value="TN" Tennessee
        option value="TX" Texas
        option value="UT" Utah
        option value="VA" Virginia
        option value="VT" Vermont
        option value="WA" Washington
        option value="WI" Wisconsin
        option value="WV" West Virginia
        option value="WY" Wyoming

app/views/distributions/index.slim
.react#distributions

app/views/distributions/new.slim
.container-fluid
.col-sm-2
.col-sm-5
	=render partial: 'distribution_form'
	=render partial: 'order'
	=render partial: 'iready_order'
	=render partial: 'ready_order'
			

app/views/distributions/show.slim
/ display summary of end_users along with distro information
.react#distribution
h2 Distribution
table.table.table-striped
  tr
    th Creation Date
    td 
      = @distribution.creation_date
  tr
    th Final Quote Id
    td 
      = @distribution.final_quote_id
  tr
    th PO Number
    td 
      = @distribution.po_number
  tr
    th District Name
    td 
      = @distribution.district.nil? ? 'error: no district' : @distribution.district.name
  tr
    th District State
    td 
      = @distribution.district.nil? ? 'error: no district' : @distribution.district.state

h2 End Users

/ TODO: put a collapsible panel here
.panel
  .panel-heading
    .panel-title
      h4 IReady Users
  .panel-body
    table.table.table-striped
      thead
        tr 
          td Contact
          td School id
          td subject
          td order_id
          td toolbox
          td enrollment
      tbody
        - @distribution.orders.each do |order|
          - if order.i_ready_orders.length > 0
            tr
              td
                = order.contact_name
              td
                = order.school_id
              - order.i_ready_orders.each do |i|
                td
                  =i.subject
                td
                  =i.order_id
                td
                  =i.toolbox
                td
                  =i.enrollment
/ TODO: put a collapsible panel here
.panel
  .panel-heading
    .panel-title
      h4 Ready Users
  .panel-body
    table.table.table-striped
      thead
        tr 
          td contact
          td school id
          td subject
          td order id
          td teacher products
          td student products
      tbody             
        - @distribution.orders.each do |order|
          - if order.ready_orders.length > 0
            tr
              td 
                = order.contact_name
              td
                = order.school_id
              - order.ready_orders.each do |r|
                td
                  = r.subject
                td
                  =r.order_id
                / grade break down 
                td
                  /TODO add collapsible r.teacher_total
                  = r.teacher_total
                td
                  /TODO add collapsible r.student_total
                  = r.student_total
                td 
                  a href="#grades" data-toggle="collapse" aria-expanded="false" aria-controls="grades" unfold detail
                tr 
                  td colspan=7
                    .collapse#grades.pull-right
                      table.table
                        thead
                            tr
                              td type
                              td grade 1
                              td grade 2
                              td grade 3
                              td grade 4
                              td grade 5
                              td grade 6
                              td grade 7
                              td grade 8
                        / teacher
                        / TODO: add a collapsible r.teacher_total
                        tr
                          td teacher
                          td
                            =r.grade_1_teacher
                          td
                            =r.grade_2_teacher
                          td
                            =r.grade_3_teacher
                          td
                            =r.grade_4_teacher
                          td
                            =r.grade_5_teacher
                          td
                            =r.grade_6_teacher
                          td
                            =r.grade_7_teacher
                          td
                            =r.grade_8_teacher
                        /student
                        / TODO: add a collapsible r.student_total
                        tr
                          td student
                          td
                            =r.grade_1_student
                          td
                            =r.grade_2_student
                          td
                            =r.grade_3_student
                          td
                            =r.grade_4_student
                          td
                            =r.grade_5_student
                          td
                            =r.grade_6_student
                          td
                            =r.grade_7_student
                          td
                            =r.grade_8_student
                