config/routes.rb
Rails.application.routes.draw do

  

  
  get 'admin/show_distributions'

  get "log_in" => "sessions#new", :as => "log_in"
  post "log_in" => "sessions#create"
  delete "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  
  post 'end_users/add_ready'
  post 'end_users/add_iready'
  post "end_users/update_ready"
  post "end_users/update_iready"
  get 'distributions/index'
  get 'distributions/edit'
  get 'distributions/create'
  get 'distributions/districts'
  post 'distributions/district_id'
  post 'distributions/update'
  root :to => "distributions#index"

  resources :distributions
  resources :districts
  resources :users

end

app/views/layouts/application.slim
<!DOCTYPE html>
html
  head
    title distroSite
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
body
  .container
    nav.navbar.navbar-light.bg-faded
      ul.nav.navbar-nav
        li class="nav-item active"
          - if current_user
            li.nav-item.active
              a.nav-link href="#"
                = current_user['username']
              
            li.nav-item
              = link_to "Log Out", {controller: 'sessions', action: 'destroy'}, :method => :delete, :class=>'nav-link'
            li.nav-item
              = link_to "See Your Distributions", {controller: 'distributions', action: 'index'}, :class=>'nav-link'
            li.nav-item
              = link_to "See All Distributions", {controller: 'admin', action: 'show_distributions'}, :class=>'nav-link'
          - else
            li.nav-item.pull-xs-right
              = link_to 'Log In', log_in_path
            li.nav-item.pull-xs-right
              =link_to "New User", "sign_up", :class=>'nav-link'
    
    = yield

= javascript_include_tag 'application', 'data-turbolinks-track' => true 